name: webdiff

type: python

up:
  - python: 3.8.2
  - pip:
    - requirements.txt

commands:
  __default__: install

  install:
    run: pip install -r requirements.txt && sudo -H python setup.py install